version: "3.9"

services:

  nginx:
    container_name: nginx
    image: nginx:1.24
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/opt/jirarush/resources/static:ro
    depends_on:
      - jira
    restart: always

  jira:
    image: project-final
    container_name: jirarush
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15.2
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    restart: always
